apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ociregistry
  namespace: external-secrets
spec:
  target:
    name: ociregistry
    deletionPolicy: Delete
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |-
          {{ .registry }}
  data:
    - secretKey: registry
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: bb4d178f-c630-43c5-8170-1d7b92dbbdd2