apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-pod-monitor.yaml

configMapGenerator:
  - name: flux-grafana-dashboards
    namespace: monitoring
    files:
      - dashboards/control-plane.json
      - dashboards/cluster.json
      - dashboards/logs.json
      - dashboards/lokisearch.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring